# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Test

on:
  push:
    branches: [ "Pane" ]
  pull_request:
    branches: [ "Pane" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: echo Hello, world!
    - name: Run tests
      run: echo Add other actions to build,
      echo test, and edploy your project
